Feature/layout
wafflestudio/snudy-web pull request #4
Opened 2022-03-06 15:35 UTC by Chang-Man

pdf 예시 시안에서 상단 표시줄과 하단 네비게이션 바 레이아웃을 만들었습니다.
좌측에 있던 바를 하단으로 옮겼고 라우팅 구조를 유지하며 MUI를 써서 공통 레이아웃을 만들어보았습니다.

한번 확인해주세요!

2022-03-07 00:58 UTC, woohm402 commented on src/App.tsx
> +import Overview from './components/snudyspace/SnudySpace';
이름 덜 바뀐 거 같아요!
```suggestion
import SnudySpace from './components/snudyspace/SnudySpace';
```

2022-03-07 00:58 UTC, woohm402 commented on src/components/layout/NavigationBar.tsx
> +    <Box sx={{ width: '100%', position: 'fixed', bottom: 0 }}>
이런 부분은 css로 처리하는 게 어떨까요? 👀

2022-03-07 00:58 UTC, woohm402 commented on src/components/layout/StatusBar.tsx
> +        alignItems: 'middle ',
여기도 css?

2022-03-07 10:47 UTC, Chang-Man commented on src/App.tsx
> +import Overview from './components/snudyspace/SnudySpace';
수정했습니다!!

2022-03-07 10:48 UTC, Chang-Man commented on src/components/layout/NavigationBar.tsx
> +    <Box sx={{ width: '100%', position: 'fixed', bottom: 0 }}>
넵 수정했습니다

2022-03-07 10:48 UTC, Chang-Man commented on src/components/layout/StatusBar.tsx
> +        alignItems: 'middle ',
수정했어용

2022-03-08 00:10 UTC, woohm402 requested changes

2022-03-08 00:10 UTC, woohm402 commented on sets by status 7.27 KiB [cached] 1 asset
> +[33mcommit f6906326ddf4718a4a58064260da92456d6a5416[m[33m ([m[1;36mHEAD -> [m[1;32mfeature/layout[m[33m, [m[1;31morigin/feature/layout[m[33m)[m
얜 뭘까요..?

2022-03-08 00:10 UTC, woohm402 commented on sets by status 7.27 KiB [cached] 1 asset
> +[33mcommit f6906326ddf4718a4a58064260da92456d6a5416[m[33m ([m[1;36mHEAD -> [m[1;32mfeature/layout[m[33m, [m[1;31morigin/feature/layout[m[33m)[m
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2022-03-08 00:10 UTC, woohm402 commented on src/components/layout/NavigationBar.tsx
> +import styles from '../../styles/NavigationBar.module.scss';
스타일 파일이 컴포넌트 옆에 있는 게 낫지 않을까요?

2022-03-08 00:10 UTC, woohm402 commented on src/components/layout/StatusBar.tsx
> +import styles from '../../styles/StatusBar.module.scss';
여기도 컴포넌트 옆에

2022-03-08 00:11 UTC, woohm402 commented on src/components/layout/NavigationBar.tsx
> +import styles from '../../styles/NavigationBar.module.scss';
스타일 파일을 이렇게 `styles/` 파일에 몰아놓으면 나중에 스타일 수정할 때마다 매번 그 폴더 찾아가야 되고, styles/ 폴더가 너무 비대해진다는 문제가 생길 거 같아요

2022-03-08 00:13 UTC, woohm402 commented on src/components/layout/NavigationBar.tsx
> +import styles from '../../styles/NavigationBar.module.scss';
결정적으로 리액트 철학인 [관심사의 분리](https://en.wikipedia.org/wiki/Separation_of_concerns)에도 맞지 않는 거 같구요

https://ko.reactjs.org/docs/introducing-jsx.html#why-jsx

2022-03-08 10:26 UTC, Chang-Man commented on sets by status 7.27 KiB [cached] 1 asset
> +[33mcommit f6906326ddf4718a4a58064260da92456d6a5416[m[33m ([m[1;36mHEAD -> [m[1;32mfeature/layout[m[33m, [m[1;31morigin/feature/layout[m[33m)[m
엥 이게 뭐죠...?ㅋㅋㅋㅋ..

2022-03-08 10:26 UTC, Chang-Man commented on src/components/layout/NavigationBar.tsx
> +import styles from '../../styles/NavigationBar.module.scss';
넵 수정했습니다!

2022-03-09 03:50 UTC, woohm402 commented on sets by status 7.27 KiB [cached] 1 asset
> +[33mcommit f6906326ddf4718a4a58064260da92456d6a5416[m[33m ([m[1;36mHEAD -> [m[1;32mfeature/layout[m[33m, [m[1;31morigin/feature/layout[m[33m)[m
ㅋㅋㅋㅋㅋ 제거해주세요!

2022-03-09 05:21 UTC, Chang-Man commented on sets by status 7.27 KiB [cached] 1 asset
> +[33mcommit f6906326ddf4718a4a58064260da92456d6a5416[m[33m ([m[1;36mHEAD -> [m[1;32mfeature/layout[m[33m, [m[1;31morigin/feature/layout[m[33m)[m
넵

2022-03-10 00:49 UTC, woohm402 approved these changes

2022-03-10 11:46 UTC, merged