Feat/snudyspace
wafflestudio/snudy-web pull request #6
Opened 2022-03-22 16:17 UTC by Chang-Man

![스크린샷, 2022-03-23 01-12-20](https://user-images.githubusercontent.com/88428193/159525055-dd46ad5c-b5fb-4a86-9819-02054eaf42d9.png)

Snudyspace 메인 페이지 구현을 했습니다.
subject를 클릭하면 해당 과목의 subject-detail로 이동이 됩니다.

라우팅 구조와 컴포넌트 구조를 지난 리뷰에서 제가 코멘트했던 것처럼 변경해보았는데, 하면서 생각해보니까 이렇게 하면 너무 복잡해지는 것 같아서 다시 되돌려놔야할 것 같네요...ㅋㅋ 일단 변경 해놓은 상태이지만 회의때 다시한번 의논해보고 다시 바꿔야할 것 같습니다!

2022-03-23 02:42 UTC, woohm402 reviewed
폴더 구조를 변경하거나 파일명을 변경하는 등의 체인지는 컨플릭에 유연하게 대응하기 힘들기 때문에 최대한 자제하는 게 좋을 거 같아요.

우선은 제가 작업중인 게 없었으니 괜찮을 거 같은데, 이후에는 요런 결정은 회의를 통해서 진행해야 할 거 같습니다 :)

2022-03-23 02:42 UTC, woohm402 commented on src/components/snudyspace/SnudySpace.tsx
> +        <Select defaultValue={0}>
요건 나중에 api 나오면 비제어 방식 -> 제어 방식으로 수정 예정이신 거 맞으실까요?

2022-03-23 02:42 UTC, woohm402 commented on src/App.tsx
> +        <Route path="/" element={<Navigate replace to="/snudyspace" />} />
논의 필요

2022-03-23 06:45 UTC, Chang-Man commented on src/components/snudyspace/SnudySpace.tsx
> +        <Select defaultValue={0}>
넵! 일단 디자인에 맞게 넣어둔거라 수정할 예정입니다

2022-03-24 00:07 UTC, woohm402 submitted a review, later dismissed

2022-03-24 00:20 UTC, woohm402 commented
1. 사용되지 않는 변수가 있는 거 같아요. 코드리뷰에서 이렇게 로우레벨의 내용을 잡는 건 비효율적이니까, eslint 의 no-unused-vars 속성을 추구 적용해보면 좋을 거 같아요

![image](https://user-images.githubusercontent.com/39977696/159816728-1ed750a4-8271-4fa7-a13a-26344ded5009.png)

2. 이 item 커스텀 css 적용해주셨는데, mui 쓰고 있으니까 [mui card](https://mui.com/components/cards/) 이용하는 게 나을 거 같아요. `article` 태그가 아니라 `div` 태그라는게 살짝 맘에 안 들긴 하지만.. 

안에 있는 텍스트도 span 말고 `Typography` 이용해 주세요!

![image](https://user-images.githubusercontent.com/39977696/159816988-e3744700-e984-4381-9827-fd6666fbcb25.png)

2022-03-24 00:20 UTC, woohm402 requested changes
!

2022-03-25 00:09 UTC, woohm402 approved these changes

2022-03-25 00:09 UTC, merged